### PR TITLE
Remove dots that breaks GitHub auto-linking

### PR DESCRIPTION
**Pull request by dentarg**
https://help.github.com/articles/autolinked-references-and-urls/

(This is naive PR, I made it on github.com and I haven't tried out the change for real, sorry for that.)

### CODE REVIEW

**Comment by dentarg** [comment]
Ah, just discovered that it is the same issue with the `This issue was moved by user from owner/repo#123."` line as well. Is this intentional? 

I didn't dare to change this line as I don't understand why it ends with `*`

https://github.com/dessant/move-issues/blob/862731898c4fe889d151ff77c78066c900832341/src/move.js#L270

**Comment by dentarg** [comment]
> I didn't dare to change this line as I don't understand why it ends with `*`

Ah, that's just Markdown.

**Comment by dessant** [comment]
:wave: Thanks for contributing! I'm not able to reproduce your issue, the links touched by this PR are parsed correctly by GitHub.

Example issues:
```
https://github.com/flutter/flutter/issues/18147
https://github.com/org1x/repo1/issues/4
```

Could you share an example where the links are broken?

**Comment by dentarg** [comment]
I’m afraid not, the move was between two private repos. I will update here if I get around to trying to reproduce it.

**Comment by dessant** [comment]
Thanks for following back, please open an issue when you get a chance to reproduce the bug. Let's close this, it's likely the solution would not be to remove the period from the end of the sentence.

**Comment by dessant** [comment]
@dentarg, I have reproduced the issue, autolinking requires read access to private repository contents. You've probably tested the markdown by editing a comment from your own account, and that's why it worked.

Issues are explicitly linked from now on to avoid requesting that permission for private repositories.

The docs list a new permission for those who deploy their own instances and need to have linking events displayed in the issue threads for private repositories.

**Comment by dentarg** [comment]
@dessant thanks for tracking it down and fixing it! 🎉

**Pull request closed without merging**
